#!/bin/bash
#SBATCH --partition short
#SBATCH --nodes 1
#SBATCH --cpus-per-task 4
#SBATCH --time 02:00:00
#SBATCH --job-name mb2-jupyter-notebook
#SBATCH -o /home/duncanc/Code/mb2_python/notebooks/jupyter_log/jupyter-notebook-%J.log
#SBATCH -e /home/duncanc/Code/mb2_python/notebooks/jupyter_log/jupyter-notebook-%J.log

# get tunneling info

node=$(hostname -s)
user=$(whoami)
NotebookPort=8999

# run jupyter notebook
jupyter-notebook --no-browser --port=${NotebookPort} --ip=${node}
